dubbo:
  application:
    name: yt-staff
    owner: fangchen
  protocol:
    name: dubbo
    port: 28887
    threads: 100
  registry:
    protocol: zookeeper
    #    address: zookeeper://test-zk.yangtuojia.com:2184?backup=test-zk.yangtuojia.com:2185,test-zk.yangtuojia.com:2186
    address: zookeeper://zk1.yangtuojia.com:2181?backup=zk2.yangtuojia.com:2181,zk3.yangtuojia.com:2181
    #    group: master
    timeout: 20000
  provider:
    retries: 0
    delay: -1
    export: true
    timeout: 5000
    group: pre
    executes: 100
  consumer:
    retries: 0
    check: false
    timeout: 10000
    group: pre
  scan:
    base-packages: com.yangt.staff

# pay.topic: yangtuo-gateway-pay-pre
# pay.tag: payNotify
log:
  location: /alidata/log/${spring.application.name}

spring:
  profiles:
    active: pre
